/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg113.project.phase.pkg2;

import javax.swing.JOptionPane;

public class InvFrame extends javax.swing.JFrame {

    /**
     * Creates new form InvFrame
     */
    
		String [] Food = {"Red Onions","Cucumber","Potatoes","Carrot","Red Apples","Oranges","Alshalan Rice","15 Eggs","Entaj Chicken","Herfy Sliced Bread white","Almarai milk 1 liter","Pepsi 360 ml","XXL Pringles Original","KitKat two fingers","Nova Water 550 ml"};
		String [] Care = { "Body Lotion","Toothbrush","Toothpaste","Face Mask","Soft Rose hand soap","Hair Shampoo","Vaseline 100 ml","Black Lash Mascara","Hair comb","Cleaning Gel for face"};
		String [] brand = {"NIVEA","sensodyne ","Sensodyne","Neutrogena"," Lux ","PANTENE","Vaseline","Essence ","wet brush","Eucerin "};
		double [] PriceFood = {4.95, 3.95,3.95,4.95, 4.95,3.95, 99.95,15,18.85,6,4,2.7,19.25,1.75,1};
		double [] PriceCare = {14,28,12,13,9.13,28.24,10,11.80,40,54.27};
    
                
    public InvFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        textBox1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setBounds(new java.awt.Rectangle(290, 120, 300, 200));

        jPanel1.setBackground(new java.awt.Color(250, 224, 224));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("What do you want to perform");

        jButton3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton3.setText("Display the products");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton4.setText("Display my Basket");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton5.setText("pay my Basket");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Add , Remove product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 14))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton1.setText("Add a product to my Basket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose product", "Red Onions", "Cucumber", "Potatoes", "Carrot", "Red Apples", "Oranges", "Alshalan Rice", "15 Eggs", "Entaj Chicken", "Herfy Sliced Bread white", "Almarai milk 1 liter", "Pepsi 360 ml", "XXL Pringles Original", "KitKat two fingers", "Nova Water 550 ml", "Body Lotion                   brand: NIVEA", "Toothbrush                    brand: sensodyne", "Toothpaste                    brand: Sensodyne", "Face Mask                      brand: Neutrogena", "Soft Rose hand soap     brand: Lux", "Hair Shampoo               brand: PANTENE", "Vaseline 100 ml             brand: Vaseline", "Black Lash Mascara        brand: Essence", "Hair comb                     brand: wet brush", "Cleaning Gel for face    brand: Eucerin" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        textBox1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        textBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBox1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton2.setText("Remove a whole product from my Basket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("Enter the Quantity:");

        jComboBox2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose product", "Red Onions", "Cucumber", "Potatoes", "Carrot", "Red Apples", "Oranges", "Alshalan Rice", "15 Eggs", "Entaj Chicken", "Herfy Sliced Bread white", "Almarai milk 1 liter", "Pepsi 360 ml", "XXL Pringles Original", "KitKat two fingers", "Nova Water 550 ml", "Body Lotion                   brand: NIVEA", "Toothbrush                    brand: sensodyne", "Toothpaste                    brand: Sensodyne", "Face Mask                      brand: Neutrogena", "Soft Rose hand soap     brand: Lux", "Hair Shampoo               brand: PANTENE", "Vaseline 100 ml             brand: Vaseline", "Black Lash Mascara        brand: Essence", "Hair comb                     brand: wet brush", "Cleaning Gel for face    brand: Eucerin" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(textBox1))
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // addProduct
        String Quantity ,productSelected;
        Quantity=textBox1.getText();
        productSelected=jComboBox1.getSelectedItem().toString();
        double pGrams=0;
        int pQuant=0 ;
       int check=0;
     

       while(check==0) {
              if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Choose product") || textBox1.getText().equalsIgnoreCase(""))//validate the user input
              {JOptionPane.showMessageDialog(null,"First You must Enter product ,and the Quantity");
              return;}
else {
       try{ 
      pGrams=Double.parseDouble(Quantity);
        pQuant =Integer.parseInt(Quantity);
    }
    
    catch (NumberFormatException e ){
        JOptionPane.showMessageDialog(null,"You must Enter a valid phone number");
        textBox1.setText("Enter the Quantity");
        return;
    }
}
        for(int r=0 ; r<6 ; r++) {
             if(Food[r].equalsIgnoreCase(productSelected)) {
                 boolean enter1=true;
                 while(enter1) {
                      try {
                         if(pGrams<=0)
			     throw new NegativQuantity();
                         enter1=false;
                         JOptionPane.showMessageDialog(this,"add successfully to your Basket");
                         }
                     catch(NegativQuantity n) { JOptionPane.showMessageDialog(null,n.toString());
                     return;}
                 }
             TestGui.customer.addProduct(new Food (PriceFood[r], Food[r], 1,pGrams));
              check++;
             break;
        }}

        for(int r=6 ; r<Food.length ; r++) {
             if(Food[r].equalsIgnoreCase(productSelected)) {
                 boolean enter1=true;
                 while(enter1) {
                      try {
                         if(pQuant<=0)
			     throw new NegativQuantity();
                         enter1=false;
                         JOptionPane.showMessageDialog(this,"add successfully to your Basket");
                         }
                     catch(NegativQuantity n) {  JOptionPane.showMessageDialog(null,n.toString());
                     return;}
                 }
            TestGui.customer.addProduct(new Food (PriceFood[r], Food[r], pQuant,0));
             check++;
            break;
        }} 
        
        for(int r=0 ; r<Care.length ; r++){
            if(Care[r].equalsIgnoreCase(productSelected)) {
                boolean enter1=true;
		while(enter1) {
		try {
                    if(pQuant<=0)
			throw new NegativQuantity();
		enter1=false;
                JOptionPane.showMessageDialog(this,"add successfully to your Basket");
                }
                catch(NegativQuantity n) { JOptionPane.showMessageDialog(null,n.toString());
                     return;}
                }
                TestGui.customer.addProduct(new Care (PriceCare[r], Care[r], pQuant,brand[r])); 
                check++;
                break;
            }
        }

        }
        
        textBox1.setText("");
        jComboBox1.setSelectedItem("Choose product");

      
            
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // remove product
        String removedProduct;
        removedProduct=jComboBox2.getSelectedItem().toString();
        
         if(jComboBox2.getSelectedItem().toString().equalsIgnoreCase("Choose product") )//validate the user input
              {JOptionPane.showMessageDialog(null,"First You must Enter product ");
              return;}
         else{
        if(  TestGui.customer.searchProduct(removedProduct)!=-1){
       TestGui.customer.removeProduct(removedProduct);
        JOptionPane.showMessageDialog(null,"Removed successfully from your Basket");}
        else{JOptionPane.showMessageDialog(null,"Can't find the product in your Basket");}
         }
       jComboBox2.setSelectedItem("Choose product");
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        listFrame flist=new listFrame();
         flist.setVisible(true);
    }                                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void textBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        printFrame fPrint =new printFrame();
        fPrint.setVisible(true);
       
    }                                        

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textBox1;
    // End of variables declaration                   
}
